# Travic-CI-Config file for Manero
#
sudo: false
language: php

php:
 - 7.1
 - 7.2
 - nightly

env:
 - DEPS=latest

matrix:
  fast_finish : true
  allow_failures:
      - php: nightly
  include:
    - php: 7.2
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
        - CHECK_CS=false

stages:
  - check
  - test
  - coverage
  - build
  - deploy

jobs:
  include:
    - stage: check
      php: 7.2
      env: DEPS=latest
      script:
        - composer cs-check
    - stage: test
    - stage: coverage
      if: branch = master AND type = push
      php: 7.2
      env: TEST_COVERAGE=true
      script: skip
      after_script:
       - travis_retry composer require $COMPOSER_ARGS --dev satooshi/php-coveralls ;
       - composer test-coverage
       - travis_retry composer upload-coverage
    - stage: build
      if: tag =~ ^[0-9]
      php: 7.2
      script:
        - composer buildphar
    - stage: deploy
      if: tag =~ ^[0-9]
      script: echo "Deploying to github"
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      file:
        - build/manero.phar
      on:
        tags: true


before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - composer test
